algoritmo "Altura e largura"
var
   altura , largura , tinta , area1 , area2 , area_total , total : real
   
inicio

   Escreval (" qual a largura da parede?")
   leia (largura)
   escreval (" qual a Altura da parede?")
   leia (altura)
   area1 <- largura* altura
   total <- area1 / 2
   escreval(" A area total é de:  " , area1 )
   escreval ( " A quantidade de litros pra ser pintada é de: " ,total)

fimalgoritmo