algoritmo "91"

var
 N1 , N2 , MAIOR: INTEIRO
 
 procedimento maior( A , b: inteiro)
  INICIO

  se(A>b) entao
     escreval("O MAIOR NÚMERO É: " ,A )
  senao
      se(A<B) entao
          escreval("O MAIOR NÚMERO É: " ,B)
      senao
          escreval("OS 2 NUMEROS SÃO IGUIAS")
      fimse
  fimse

 
 
 fimprocedimento
 
inicio
   ESCreva ("digite O PRIMEIRO um numero : ")
   leia (n1)
   escreva("digite O SEGUNDO numero: ")
   leia(n2)
   maior (n1 , n2 )
   
   
fimalgoritmo