algoritmo "94 Proximo Fibonnaci"
var
   n , c, t1 ,t2 ,t3:inteiro
procedimento proximofibonacci( var a,b :inteiro)
var c:inteiro
inicio

   c:= a+b
   escreva(c," >>>")
   A:= b
   b:= c
fimprocedimento
inicio
   escreval(" Deseja ir ate que numero : ")
   leia(n)
   limpatela
   t1<- 1
   escreva(t1 ," >>>")
   t2 <-1
   escreva(t2," >>>")
   para c:=3 ate N faca
      proximofibonacci(t1 ,t2)
   fimpara
   ESCREVA(" FIM")


fimalgoritmo