algoritmo "calculo - idade com condicional"
var

   ano , nasc , idade : inteiro

inicio

      Escreva(" em que ano estamos?")
      leia (ano)
      escreva (" Em que ano você nasceu?")
      leia (nasc)
      idade <- ano-nasc
      escreval (" em ", ano , " você tera  ", idade , "Anos")
      Se (idade >= 18 ) entao
      escreval (" você ja atingiu a maior idade")
     // senao
      //escreval( " você   ainda não tera atingindo a maior idade")
      fimse
fimalgoritmo