algoritmo "SOMA DE n PARES-REPETICOES"
var
   N, CONTADOR, NPAR , NIMPAR :INTEIRO
inicio
   CONTADOR<-1
   npar<- 0
   nimpar<-0
   ENQUANTO (CONTADOR<=6) FACA
      ESCREVA (" Digite um Número :")
      leia (N)
      contador<-contador +1)
      se (n%2=0) entao
       npar<- npar+1
    senao
       nimpar<- nimpar+1
    fimse
   fimenquanto

    escreval("Numeros par ", npar)
    escreval ("numeros impar", nimpar)
fimalgoritmo