algoritmo "somaparametrosreferencia"
var
   x , Y :inteiro
Procedimento soma(var a,b: inteiro)  //com a variavel var os valores de x e y serão atualizados
inicio
   A<- A+1
   b <- B+1
   escreval(" Valor de A= ", A)
   Escreval(" Valor de B = ", B)
   escreval("soma de A + B = ",A+b)
fimprocedimento
inicio
   x<- 5
   y<-  6
   soma (x ,y)
   escreval(" Valor de x= " ,x)
   Escreval (" Valor de Y = ", y)


fimalgoritmo